#aliases for easily updating modules
alias eam="em alias-modules"
alias ema="em apt"
alias emd="em docker"
alias emds="em disk"
alias emf="em functions"
alias emfz="em fzf"
alias emfs="em fzf-ssh"
alias emg="em git"
alias emh="em history"
alias emm="em mysql"
alias emp="em prompt"
alias ems="em ssh"
alias emsrv="em servers"
alias emt="em tar"
alias emv="em vultr"
